# **Google-PlayStore Dataset**

# **Context**
Google playstore dataset having record of 2.3M+ Applications

# **Overviewing DataSet**

In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [65]:
df=pd.read_csv('Google-Playstore.csv')

In [66]:
df.head(10)

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,...,Developer Website,Developer Email,Released,Last Updated,Content Rating,Privacy Policy,Ad Supported,In App Purchases,Editors Choice,Scraped Time
0,Gakondo,com.ishakwe.gakondo,Adventure,0.0,0.0,10+,10.0,15,True,0.0,...,https://beniyizibyose.tk/#/,jean21101999@gmail.com,"Feb 26, 2020","Feb 26, 2020",Everyone,https://beniyizibyose.tk/projects/,False,False,False,2021-06-15 20:19:35
1,Ampere Battery Info,com.webserveis.batteryinfo,Tools,4.4,64.0,"5,000+",5000.0,7662,True,0.0,...,https://webserveis.netlify.app/,webserveis@gmail.com,"May 21, 2020","May 06, 2021",Everyone,https://dev4phones.wordpress.com/licencia-de-uso/,True,False,False,2021-06-15 20:19:35
2,Vibook,com.doantiepvien.crm,Productivity,0.0,0.0,50+,50.0,58,True,0.0,...,NaN,vnacrewit@gmail.com,"Aug 9, 2019","Aug 19, 2019",Everyone,https://www.vietnamairlines.com/vn/en/terms-an...,False,False,False,2021-06-15 20:19:35
3,Smart City Trichy Public Service Vehicles 17UC...,cst.stJoseph.ug17ucs548,Communication,5.0,5.0,10+,10.0,19,True,0.0,...,http://www.climatesmarttech.com/,climatesmarttech2@gmail.com,"Sep 10, 2018","Oct 13, 2018",Everyone,NaN,True,False,False,2021-06-15 20:19:35
4,GROW.me,com.horodyski.grower,Tools,0.0,0.0,100+,100.0,478,True,0.0,...,http://www.horodyski.com.pl,rmilekhorodyski@gmail.com,"Feb 21, 2020","Nov 12, 2018",Everyone,http://www.horodyski.com.pl,False,False,False,2021-06-15 20:19:35
5,IMOCCI,com.imocci,Social,0.0,0.0,50+,50.0,89,True,0.0,...,http://www.imocci.com,info@imocci.com,"Dec 24, 2018","Dec 20, 2019",Teen,https://www.imocci.com/wp-content/uploads/2018...,False,True,False,2021-06-15 20:19:35
6,unlimited 4G data prank free app,getfreedata.superfatiza.unlimitedjiodataprank,Libraries & Demo,4.5,12.0,"1,000+",1000.0,2567,True,0.0,...,NaN,aitomgharfatimezzahra@gmail.com,"Sep 23, 2019","Sep 27, 2019",Everyone,https://sites.google.com/view/unlimited4gdatap...,True,False,False,2021-06-15 20:19:35
7,The Everyday Calendar,com.mozaix.simoneboard,Lifestyle,2.0,39.0,500+,500.0,702,True,0.0,...,NaN,elementuser03@gmail.com,"Jun 21, 2019","Jun 21, 2019",Everyone,https://www.freeprivacypolicy.com/privacy/view...,False,False,False,2021-06-15 20:19:35
8,WhatsOpen,com.whatsopen.app,Communication,0.0,0.0,10+,10.0,18,True,0.0,...,http://yilvermolinah.com,yilver.mh1996@gmail.com,NaN,"Dec 07, 2018",Teen,http://elcafedelamanana.yilvermolinah.com/poli...,False,False,False,2021-06-15 20:19:35
9,Neon 3d Iron Tech Keyboard Theme,com.ikeyboard.theme.neon_3d.iron.tech,Personalization,4.7,820.0,"50,000+",50000.0,62433,True,0.0,...,https://trendyteme888-31139.web.app,trendyteme.888@gmail.com,"Sep 22, 2019","Oct 07, 2020",Everyone,http://bit.ly/EmojiThemePro,True,False,False,2021-06-15 20:19:35

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2312944 entries, 0 to 2312943
Data columns (total 24 columns):
 #   Column             Dtype
---  ------             -----
 0   App Name           object
 1   App Id             object
 2   Category           object
 3   Rating             float64
 4   Rating Count       float64
 5   Installs           object
 6   Minimum Installs   float64
 7   Maximum Installs   int64
 8   Free               bool
 9   Price              float64
 10  Currency           object
 11  Size               object
 12  Minimum Android    object
 13  Developer Id       object
 14  Developer Website  object
 15  Developer Email    object
 16  Released           object
 17  Last Updated       object
 18  Content Rating     object
 19  Privacy Policy     object
 20  Ad Supported       bool
 21  In App Purchases   bool
 22  Editors Choice     bool
 23  Scraped Time       object
dtypes: bool(4), float64(4), int64(1), object(15)
memory usage: 361.8+ MB

In [68]:
df.isnull().sum()

App Name                  5
App Id                    0
Category                  0
Rating                22883
Rating Count          22883
Installs                107
Minimum Installs        107
Maximum Installs          0
Free                      0
Price                     0
Currency                135
Size                    196
Minimum Android        6530
Developer Id             33
Developer Website    760835
Developer Email          31
Released              71053
Last Updated              0
Content Rating            0
Privacy Policy       420953
Ad Supported              0
In App Purchases          0
Editors Choice            0
Scraped Time              0
dtype: int64

In [69]:
df.shape

(2312944, 24)

In [70]:
420953/2312944*100

18.19987859628249

In [71]:
len(df)

2312944

In [72]:
df.isnull().sum()/len(df)*100

App Name              0.000216
App Id                0.000000
Category              0.000000
Rating                0.989345
Rating Count          0.989345
Installs              0.004626
Minimum Installs      0.004626
Maximum Installs      0.000000
Free                  0.000000
Price                 0.000000
Currency              0.005837
Size                  0.008474
Minimum Android       0.282324
Developer Id          0.001427
Developer Website    32.894657
Developer Email       0.001340
Released              3.071972
Last Updated          0.000000
Content Rating        0.000000
Privacy Policy       18.199879
Ad Supported          0.000000
In App Purchases      0.000000
Editors Choice        0.000000
Scraped Time          0.000000
dtype: float64

In [73]:
df.describe()

,Rating,Rating Count,Minimum Installs,Maximum Installs,Price
count,2.290061e+06,2.290061e+06,2.312837e+06,2.312944e+06,2.312944e+06
mean,2.203152e+00,2.864839e+03,1.834452e+05,3.202017e+05,1.034992e-01
std,2.106223e+00,2.121626e+05,1.513144e+07,2.355495e+07,2.633127e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.000000e+00,0.000000e+00,5.000000e+01,8.400000e+01,0.000000e+00
50%,2.900000e+00,6.000000e+00,5.000000e+02,6.950000e+02,0.000000e+00
75%,4.300000e+00,4.200000e+01,5.000000e+03,7.354000e+03,0.000000e+00
max,5.000000e+00,1.385576e+08,1.000000e+10,1.205763e+10,4.000000e+02

In [74]:
df['Currency'].value_counts()

Currency
USD    2311548
XXX       1236
EUR          6
INR          5
GBP          3
CAD          2
VND          1
BRL          1
KRW          1
TRY          1
RUB          1
SGD          1
AUD          1
PKR          1
ZAR          1
Name: count, dtype: int64

In [75]:
df['Size']

0           10M
1          2.9M
2          3.7M
3          1.8M
4          6.2M
           ...
2312939     77M
2312940     44M
2312941     29M
2312942     10M
2312943    5.2M
Name: Size, Length: 2312944, dtype: object

In [76]:
df.isnull().sum()

App Name                  5
App Id                    0
Category                  0
Rating                22883
Rating Count          22883
Installs                107
Minimum Installs        107
Maximum Installs          0
Free                      0
Price                     0
Currency                135
Size                    196
Minimum Android        6530
Developer Id             33
Developer Website    760835
Developer Email          31
Released              71053
Last Updated              0
Content Rating            0
Privacy Policy       420953
Ad Supported              0
In App Purchases          0
Editors Choice            0
Scraped Time              0
dtype: int64

In [77]:
print(f"Sum containing M : {df['Size'].loc[df['Size'].str.contains('M', na=False)].value_counts().sum()}")

Sum containing M : 2201705

In [78]:
print(f"Sum containing k : {df['Size'].loc[df['Size'].str.contains('k', na=False)].value_counts().sum()}")

Sum containing k : 36253

In [79]:
print(f"Sum containing G : {df['Size'].loc[df['Size'].str.contains('G', na=False)].value_counts().sum()}")

Sum containing G : 13

In [80]:
print(f"Sum containing Varies With Device : {df['Size'].loc[df['Size'].str.contains('Varies with device', na=False)].value_counts().sum()}")

Sum containing Varies With Device : 74777

In [81]:
2201705+36253+74777+13

2312748

In [82]:
def re_size(size):
    if isinstance(size,str):
        size=size.replace(',','')
        if 'M' in size:
            return float(size.replace('M',''))
        elif 'k'in size:
            return float(size.replace('k',''))
        elif 'G' in size:
            return float(size.replace('G',''))
        elif 'Varies with device' in size:
            return np.nan
        return size

In [83]:
df['Size']=df['Size'].apply(re_size)

In [84]:
df['Size']

0          10.0
1           2.9
2           3.7
3           1.8
4           6.2
           ...
2312939    77.0
2312940    44.0
2312941    29.0
2312942    10.0
2312943     5.2
Name: Size, Length: 2312944, dtype: float64

In [85]:
df.isnull().sum()/len(df)*100

App Name              0.000216
App Id                0.000000
Category              0.000000
Rating                0.989345
Rating Count          0.989345
Installs              0.004626
Minimum Installs      0.004626
Maximum Installs      0.000000
Free                  0.000000
Price                 0.000000
Currency              0.005837
Size                  3.241453
Minimum Android       0.282324
Developer Id          0.001427
Developer Website    32.894657
Developer Email       0.001340
Released              3.071972
Last Updated          0.000000
Content Rating        0.000000
Privacy Policy       18.199879
Ad Supported          0.000000
In App Purchases      0.000000
Editors Choice        0.000000
Scraped Time          0.000000
dtype: float64

In [86]:
df.describe()

,Rating,Rating Count,Minimum Installs,Maximum Installs,Price,Size
count,2.290061e+06,2.290061e+06,2.312837e+06,2.312944e+06,2.312944e+06,2.237971e+06
mean,2.203152e+00,2.864839e+03,1.834452e+05,3.202017e+05,1.034992e-01,2.717183e+01
std,2.106223e+00,2.121626e+05,1.513144e+07,2.355495e+07,2.633127e+00,7.563865e+01
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
25%,0.000000e+00,0.000000e+00,5.000000e+01,8.400000e+01,0.000000e+00,5.200000e+00
50%,2.900000e+00,6.000000e+00,5.000000e+02,6.950000e+02,0.000000e+00,1.100000e+01
75%,4.300000e+00,4.200000e+01,5.000000e+03,7.354000e+03,0.000000e+00,2.600000e+01
max,5.000000e+00,1.385576e+08,1.000000e+10,1.205763e+10,4.000000e+02,1.024000e+03

In [87]:
df['Size'].isnull().sum()

np.int64(74973)

In [88]:
df[df["Installs"].isnull()].head(10)

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,...,Developer Website,Developer Email,Released,Last Updated,Content Rating,Privacy Policy,Ad Supported,In App Purchases,Editors Choice,Scraped Time
5622,Claire’s Café: Tasty Cuisine 🥞🧁🍔,com.gamehouse.cc1,Casual,NaN,NaN,NaN,NaN,1023,False,0.0,...,https://www.gamehouseoriginalstories.com,ghos@gamehouse.com,NaN,"Jun 10, 2021",Everyone 10+,https://www.gamehouseoriginalstories.com/stati...,False,False,False,2021-06-15 20:25:00
43569,Potato Smash,com.igg.android.projectpotato,Strategy,NaN,NaN,NaN,NaN,72087,False,0.0,...,https://www.igg.com,help.potatosmash.android@igg.com,NaN,"Jun 11, 2021",Everyone,https://policies.igg.com/privacy_policy,True,False,False,2021-06-15 21:02:51
60888,SketchBook : Draw Art & Paints,com.sketchbook.illustrations,Art & Design,NaN,NaN,NaN,NaN,2,False,0.0,...,http://www.craox.com,nikhil@craox.com,NaN,"May 27, 2021",Everyone,NaN,True,False,False,2021-06-15 21:19:59
64322,Shared grocery Shopping List,com.tikamori.shoppinglist,Shopping,NaN,NaN,NaN,NaN,0,False,0.0,...,NaN,tikamoriapps@gmail.com,NaN,"May 18, 2021",Everyone,NaN,False,False,False,2021-06-15 21:23:23
91391,NBA NOW 21,com.com2us.nbanow2.android.google.global.normal,Sports,NaN,NaN,NaN,NaN,2,False,0.0,...,http://www.withhive.com,info@com2us.com,NaN,"May 25, 2021",Everyone,http://terms.withhive.com/terms/mobile/policy....,True,False,False,2021-06-15 21:50:02
97327,Idle Distiller - A Business Tycoon Game,com.kanoapps.bz,Simulation,NaN,NaN,NaN,NaN,2145,False,0.0,...,https://www.kanoapps.com,idle.distiller.support@kanoapps.com,NaN,"Jun 08, 2021",Teen,https://www.kanoapps.com/privacy-policy,True,False,False,2021-06-15 21:55:47
98053,Nightmare Gate: Horror show in the hell,com.IndieFist.HorrorGames.NightmareGate,Adventure,NaN,NaN,NaN,NaN,0,False,0.0,...,https://indiefist.com,media@indiefist.com,NaN,"Apr 09, 2021",Teen,NaN,True,False,False,2021-06-15 21:56:28
122978,Zombie Wasteland Adventure,com.daviddickball.zombiewasteland,Adventure,NaN,NaN,NaN,NaN,2948,False,0.0,...,https://davidonionball.itch.io/,david@ongoingworlds.com,NaN,"Mar 14, 2021",Everyone 10+,https://docs.google.com/document/d/1nP3zjhkRkd...,False,False,False,2021-06-15 22:20:26
123356,Redecor-Mansion Story,com.fotoable.villascrusher,Casual,NaN,NaN,NaN,NaN,8930,False,0.0,...,NaN,mansionstory@fotoable.com,NaN,"May 26, 2021",Teen,http://privacy.betta-games.net/,False,False,False,2021-06-15 22:20:48
148212,リヴリーアイランド ペットと暮らす小さな島,jp.cocone.livly,Social,NaN,NaN,NaN,NaN,0,False,0.0,...,NaN,support@livly.zendesk.com,NaN,"Jun 08, 2021",Everyone,https://livlyinfo.com/policy,False,False,False,2021-06-15 22:45:38

In [89]:
df.isnull().sum()

App Name                  5
App Id                    0
Category                  0
Rating                22883
Rating Count          22883
Installs                107
Minimum Installs        107
Maximum Installs          0
Free                      0
Price                     0
Currency                135
Size                  74973
Minimum Android        6530
Developer Id             33
Developer Website    760835
Developer Email          31
Released              71053
Last Updated              0
Content Rating            0
Privacy Policy       420953
Ad Supported              0
In App Purchases          0
Editors Choice            0
Scraped Time              0
dtype: int64

In [90]:
df[df['App Name'].isnull()].head(10)
df.dropna(subset='App Name',inplace=True)

In [91]:
df.isnull().sum()

App Name                  0
App Id                    0
Category                  0
Rating                22883
Rating Count          22883
Installs                107
Minimum Installs        107
Maximum Installs          0
Free                      0
Price                     0
Currency                135
Size                  74973
Minimum Android        6530
Developer Id             33
Developer Website    760831
Developer Email          31
Released              71053
Last Updated              0
Content Rating            0
Privacy Policy       420950
Ad Supported              0
In App Purchases          0
Editors Choice            0
Scraped Time              0
dtype: int64

In [92]:
760831/2312939*100

32.89455536873216

In [93]:
df.drop('Developer Website',axis=1,inplace=True)

In [94]:
df[df['Currency'].isnull()].head(50)

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,...,Developer Id,Developer Email,Released,Last Updated,Content Rating,Privacy Policy,Ad Supported,In App Purchases,Editors Choice,Scraped Time
5622,Claire’s Café: Tasty Cuisine 🥞🧁🍔,com.gamehouse.cc1,Casual,NaN,NaN,NaN,NaN,1023,False,0.0,...,GameHouse Original Stories,ghos@gamehouse.com,NaN,"Jun 10, 2021",Everyone 10+,https://www.gamehouseoriginalstories.com/stati...,False,False,False,2021-06-15 20:25:00
43569,Potato Smash,com.igg.android.projectpotato,Strategy,NaN,NaN,NaN,NaN,72087,False,0.0,...,SkyRise Digital Pte. Ltd.,help.potatosmash.android@igg.com,NaN,"Jun 11, 2021",Everyone,https://policies.igg.com/privacy_policy,True,False,False,2021-06-15 21:02:51
60888,SketchBook : Draw Art & Paints,com.sketchbook.illustrations,Art & Design,NaN,NaN,NaN,NaN,2,False,0.0,...,CRAOX TECHNOLOGIES LLP,nikhil@craox.com,NaN,"May 27, 2021",Everyone,NaN,True,False,False,2021-06-15 21:19:59
64322,Shared grocery Shopping List,com.tikamori.shoppinglist,Shopping,NaN,NaN,NaN,NaN,0,False,0.0,...,Tikamori,tikamoriapps@gmail.com,NaN,"May 18, 2021",Everyone,NaN,False,False,False,2021-06-15 21:23:23
71021,Squatz Fitness,com.gaming.squatz,Health & Fitness,0.0,0.0,"1,000+",1000.0,1768,False,0.0,...,Squatz LLC,support@squatz.com,"Aug 28, 2020","Apr 27, 2021",Everyone,https://squatz.com/privacy-policy/,False,False,False,2021-06-15 21:29:53
91391,NBA NOW 21,com.com2us.nbanow2.android.google.global.normal,Sports,NaN,NaN,NaN,NaN,2,False,0.0,...,Com2uS,info@com2us.com,NaN,"May 25, 2021",Everyone,http://terms.withhive.com/terms/mobile/policy....,True,False,False,2021-06-15 21:50:02
97327,Idle Distiller - A Business Tycoon Game,com.kanoapps.bz,Simulation,NaN,NaN,NaN,NaN,2145,False,0.0,...,KANO/APPS,idle.distiller.support@kanoapps.com,NaN,"Jun 08, 2021",Teen,https://www.kanoapps.com/privacy-policy,True,False,False,2021-06-15 21:55:47
98053,Nightmare Gate: Horror show in the hell,com.IndieFist.HorrorGames.NightmareGate,Adventure,NaN,NaN,NaN,NaN,0,False,0.0,...,IndieFist Horror Games,media@indiefist.com,NaN,"Apr 09, 2021",Teen,NaN,True,False,False,2021-06-15 21:56:28
122978,Zombie Wasteland Adventure,com.daviddickball.zombiewasteland,Adventure,NaN,NaN,NaN,NaN,2948,False,0.0,...,David Dick Ball,david@ongoingworlds.com,NaN,"Mar 14, 2021",Everyone 10+,https://docs.google.com/document/d/1nP3zjhkRkd...,False,False,False,2021-06-15 22:20:26
123356,Redecor-Mansion Story,com.fotoable.villascrusher,Casual,NaN,NaN,NaN,NaN,8930,False,0.0,...,Betta Games,mansionstory@fotoable.com,NaN,"May 26, 2021",Teen,http://privacy.betta-games.net/,False,False,False,2021-06-15 22:20:48
148212,リヴリーアイランド ペットと暮らす小さな島,jp.cocone.livly,Social,NaN,NaN,NaN,NaN,0,False,0.0,...,COCONE,support@livly.zendesk.com,NaN,"Jun 08, 2021",Everyone,https://livlyinfo.com/policy,False,False,False,2021-06-15 22:45:38
157037,Hero Avengers,com.youli.heroavengers,Role Playing,NaN,NaN,NaN,NaN,0,False,0.0,...,Fun+++,heroavengers@feiyu.com,NaN,"May 21, 2021",Teen,https://passport-oversea.737.com/clause/privacy/,False,False,False,2021-06-15 22:54:23
159084,Clash of Minions,com.igg.android.clashofminions,Role Playing,NaN,NaN,NaN,NaN,0,False,0.0,...,SkyRise Digital Pte. Ltd.,help.clashofminions.android@igg.com,NaN,"Mar 24, 2021",Teen,https://policies.skyriseonline.com/privacy_pol...,True,False,False,2021-06-15 22:56:21
162607,Puntos Colombia,com.pco.app.cliente,Shopping,3.8,600.0,"100,000+",100000.0,355352,False,0.0,...,Puntos Colombia S.A.S.,servicioalcliente@puntoscolombia.com,"Oct 20, 2020","May 03, 2021",Everyone,https://www.puntoscolombia.com/legal/personas/...,False,False,False,2021-06-15 23:00:29
164974,Images of Love with Scraps,com.apptolima.imagendeamor1,Lifestyle,0.0,0.0,500+,500.0,779,False,0.0,...,Alneiro Lozano Prieto,alneirolozanoprieto@gmail.com,"Aug 14, 2016","Jul 29, 2019",Teen,https://apper.apperalinstante.com/apptolima/po...,True,False,False,2021-06-15 23:03:41
167083,aftab,com.goodbarber.aftab,Lifestyle,4.2,17.0,"1,000+",1000.0,1339,False,0.0,...,Mohammad Hamidi,app@aftab.eu,"Jul 27, 2016","Oct 25, 2016",Everyone,http://aftab.goodbarber.com/docs/Haftungsaussc...,True,False,False,2021-06-15 23:06:33
169889,Lubbock Avalanche-Journal Print Edition,com.lubbockavalanchejournal.android.prod,News & Magazines,NaN,NaN,100+,100.0,198,False,0.0,...,Gannett,mobilesupport@gannett.com,"Feb 25, 2021","Jun 07, 2021",Everyone 10+,http://lubbockonline.tx.newsmemory.com/policy....,True,False,False,2021-06-15 23:09:47
178737,Mafia Crime War,com.onemt.mafiacrimewar,Role Playing,NaN,NaN,NaN,NaN,21592,False,0.0,...,ONEMT,servicemcw@onemt.com,NaN,"Apr 28, 2021",Mature 17+,http://www.onemt.com/abroadgame/outer/policy,False,False,False,2021-06-15 23:19:29
179760,New Heist Thief Simulator 2021 : New Robbery Plan,com.hsg.sneak.thief.simulator.robbery.plan,Weather,4.0,1360.0,"100,000+",100000.0,312777,False,0.0,...,Perfect Gamers Hub,theperfectgamershub@gmail.com,"Mar 4, 2019","Jun 01, 2021",Teen,https://sites.google.com/view/lightbolt-privac...,True,True,False,2021-06-15 23:21:14
185164,Online Indian Girls Chat Meet,com.online.indiangirlschat.meet,Dating,5.0,54.0,500+,500.0,725,False,0.0,...,Codeentechnologies,sadateensadatkopak@gmail.com,"Oct 12, 2020","Oct 12, 2020",Mature 17+,http://www.e-droid.net/privacy.php?ida=1248120...,True,False,False,2021-06-15 23:28:07
189151,AMAZING FLY PUNCH,com.gpureturn.amazingflypunch,Action,0.0,0.0,10+,10.0,28,False,0.0,...,GPU_RETURNS,gpu.returns@gmail.com,"Sep 7, 2018","Oct 05, 2018",Teen,NaN,False,False,False,2021-06-15 23:32:17
190484,Snickometer : Cricket Prediction Tool,com.snickometer.cricket,Sports,2.6,24.0,"5,000+",5000.0,7944,False,0.0,...,Box Car Digital,adaschmidt89@gmail.com,"Nov 15, 2018","May 07, 2021",Everyone,http://boxcar.digital/privacypolicies/snickome...,True,False,False,2021-06-15 23:33:42
199448,Lil Miss know it all Psychic,miss.know.it.all,Social,NaN,NaN,NaN,NaN,3,False,0.0,...,Cspeer246,cspeer246@gmail.com,NaN,"Jun 04, 2021",Teen,http://www.e-droid.net/privacy.php?ida=1501269...,True,False,False,2021-06-15 23:42:37
201924,Magic Revenge：Casual IDLE RPG,com.tojoy.magicrevenge,Role Playing,NaN,NaN,NaN,NaN,218435,False,0.0,...,TOJOY GAME,magirevenge@gmail.com,NaN,"Apr 20, 2021",Teen,http://jp.tojoygame.com/policy.html,True,False,False,2021-06-15 23:44:59
210179,IFMA San Antonio Chapter,com.viethconsulting.SAFMmainapp,Business,0.0,0.0,100+,100.0,209,False,0.0,...,Vieth Consulting,apps@viethconsulting.com,"Apr 28, 2014","Feb 22, 2017",Everyone,http://www.viethconsulting.com/Privacy.PDF,False,False,False,2021-06-15 23:53:04
216171,INEA,pl.inea,Tools,2.8,480.0,"100,000+",100000.0,109681,False,0.0,...,INEA S.A.,aplikacja_mobilna@inea.com.pl,"Apr 13, 2018","Feb 15, 2021",Everyone,https://www.inea.pl/o-inea/o-nas/polityka-pryw...,False,False,False,2021-06-16 00:00:25
225893,Jardins de Tréville,fr.astrance.mousquetairesAndroid,Travel & Local,4.9,7.0,100+,100.0,203,False,0.0,...,arp-astrance,hmoal@arp-astrance.com,"Nov 16, 2017","Jan 16, 2018",Everyone,https://www.dropbox.com/s/61r9l8djgau2fz7/CHAR...,False,False,False,2021-06-16 00:11:27
227869,EPO 2019,mobile.appzGs4pHkOOn,Business,NaN,NaN,50+,50.0,93,False,0.0,...,Energy Professionals of Ohio,meredith@fusefive.com,"Oct 14, 2019","Oct 14, 2019",Everyone,http://www.energyprofessionalsofohio.com/priva...,True,False,False,2021-06-16 00:14:20
228320,Super Nova Institute,co.lynde.lbyld,Education,4.4,5.0,100+,100.0,140,False,0.0,...,Education Mobile Media,support@classplus.co,"May 23, 2020","Jun 08, 2021",Everyone,https://bit.ly/2YDTip0,True,False,False,2021-06-16 00:14:55
229880,Mystic Gunner: Roguelike Shooting Action Adven...,com.buffstudio.isword.mystic.gunner.rougelike....,Action,NaN,NaN,NaN,NaN,2778,False,0.0,...,"Buff Studio (Story Games, Calm Games)",help@buffstudio.com,NaN,"Jun 14, 2021",Everyone 10+,http://www.buffstudio.com/?page_id=403,True,False,False,2021-06-16 00:17:06
243990,Fine Deal,com.mexilet.ecommp.finedeal,Shopping,0.0,0.0,10+,10.0,11,False,0.0,...,Mexilet Technologies Pvt Ltd,finedeal.co.in@gmail.com,"Jun 1, 2020","Jun 01, 2020",Everyone,https://www.mexilet.com/privacypolicy/,False,False,False,2021-06-16 00:31:53
249798,Word Chef,com.pacific.wordchef,Puzzle,NaN,NaN,NaN,NaN,1,False,0.0,...,Pacific Enterprises,mobile@pacific.enterprises,NaN,"Sep 21, 2018",Everyone,NaN,True,False,False,2021-06-16 00:37:40
257308,Wordjamacallit,com.hotchaipro.matchwords,Word,NaN,NaN,NaN,NaN,5,False,0.0,...,"Hot Chai Productions, LLC",support@hotchaipro.com,NaN,"Jun 15, 2021",Everyone,NaN,False,False,False,2021-06-16 00:44:46
269748,古惑仔M：我最大、我話事！,com.gameone.tbm,Role Playing,NaN,NaN,NaN,NaN,0,False,0.0,...,GAMEONE GROUP LIMITED,csjz@gameone.com,NaN,"Jun 11, 2021",Everyone 10+,http://gameone.com/p_info2.php,False,False,False,2021-06-16 00:56:43
271000,SHS Auto Parts,com.insitusales.b2becommerce.shsautoparts,Shopping,NaN,NaN,10+,10.0,18,False,0.0,...,inSitu Mobile,support@insitusales.com,"Sep 15, 2020","Sep 15, 2020",Everyone,https://shsautoparts.b2bmobilesales.com/privac...,False,False,False,2021-06-16 00:57:57
322492,Haydos 380,com.creativemonkeygames.haydos380cricket,Sports,NaN,NaN,NaN,NaN,9,False,0.0,...,Creative Monkey Games,creativemonkey.games@gmail.com,NaN,"Jun 07, 2021",Everyone,http://creativemonkeygames.com/privacy-policy/,True,False,False,2021-06-16 01:51:18
326450,KDE Itinerary,org.kde.itinerary,Travel & Local,NaN,NaN,NaN,NaN,0,False,0.0,...,KDE Community,kde-pim@kde.org,NaN,"May 29, 2021",Everyone,https://community.kde.org/KDEConnect/PrivacyPo...,False,False,False,2021-06-16 01:55:07
337442,Empire Defender TD: Tower Defense The Kingdom ...,com.empire.warriors2.epic.tower.td.defender.rush,Strategy,NaN,NaN,NaN,NaN,36434,False,0.0,...,ZITGA,marketing@zitga.com.vn,NaN,"May 09, 2021",Everyone 10+,https://docs.google.com/document/d/1ZGlKsarN5y...,True,False,False,2021-06-16 02:05:49
340230,Infusion AI Art - Find Your Inspiration,insightfulai.infusion,Art & Design,NaN,NaN,NaN,NaN,16,False,0.0,...,Increditastic,insightfulai@gmail.com,NaN,"May 01, 2021",Everyone,NaN,False,False,False,2021-06-16 02:08:28
345578,Social Comics,br.com.socialcomics.app,Entertainment,NaN,NaN,NaN,NaN,55018,False,0.0,...,Social Comics,contato@socialcomics.com.br,"Aug 21, 2015","Jun 12, 2021",Everyone,https://beta.socialcomics.com.br/politica-de-p...,False,False,False,2021-06-16 02:13:28
354378,Basketrio: Back in the Game,com.gametaiwan.jjna,Sports,NaN,NaN,NaN,NaN,0,False,0.0,...,ALL9FUN Limited,gametw2021@gmail.com,NaN,"May 12, 2021",Everyone,NaN,True,False,False,2021-06-16 02:21:45
367097,Tales of the Mirror,com.lilithgames.themirror.gp,Puzzle,NaN,NaN,NaN,NaN,0,False,0.0,...,LilithGames,themirror-service@lilith.com,NaN,"Jun 07, 2021",Teen,https://www.lilithgames.com/privacy?locale=en-US,False,False,False,2021-06-16 02:34:07
389418,Bibi.Pet Pixel and Tangram Games for Baby,bibi.pet.kids.pixel.tangram,Educational,NaN,NaN,NaN,NaN,0,False,0.0,...,Bibi.Pet - Toddlers Games - Colors and Shapes,info@bibi.pet,NaN,"May 28, 2021",Everyone,https://www.bibi.pet/privacy,False,False,False,2021-06-16 02:55:08
404089,Atelier Online: Alchemist of Bressisle,com.boltrend.atelieren,Role Playing,NaN,NaN,NaN,NaN,6782,False,0.0,...,Boltrend Games,customer_service@boltrend.com,NaN,"Jun 02, 2021",Teen,https://www.boltrend.com/html/policy-en.html,False,False,False,2021-06-16 03:08:54
476290,Klever Exchange,io.klever.secure.exchange,Finance,NaN,NaN,NaN,NaN,1402,False,0.0,...,"Klever Wallet: Bitcoin, Ethereum, TRX & Crypto",feedback@klever.io,NaN,"Jun 14, 2021",Everyone,https://klever.io,False,False,False,2021-06-16 04:13:56
497176,Magic Duel,com.superlink.magicduel,Strategy,NaN,NaN,NaN,NaN,0,False,0.0,...,Superlink,superlink.page@gmail.com,NaN,"May 31, 2021",Teen,http://211.110.61.79:8800/,True,False,False,2021-06-16 04:32:49
522636,SwirlWalls: Interactive Wallpaper Backgrounds,com.actionwalls.swirlwalls,Personalization,NaN,NaN,NaN,NaN,0,False,0.0,...,ActionWalls,support@actionlauncher.com,NaN,"Apr 28, 2021",Everyone,NaN,True,False,False,2021-06-16 04:55:28
602384,FINAL FANTASY VII THE FIRST SOLDIER,com.square_enix.android_googleplay.ff7fsww,Action,NaN,NaN,NaN,NaN,31670,False,0.0,...,"SQUARE ENIX Co.,Ltd.",android_support@square-enix.com,NaN,"May 30, 2021",Teen,https://www.jp.square-enix.com/privacy/,False,False,False,2021-06-16 06:07:22
630153,"Midsomer Murders: Words, Crime & Mystery",com.qiiwi.midsomermurders,Word,NaN,NaN,NaN,NaN,2830,False,0.0,...,Qiiwi Games AB,support@qiiwi.com,NaN,"Jun 10, 2021",Teen,https://www.qiiwi.com/privacy-policy,True,False,False,2021-06-16 06:32:34
681921,Party Royale Animals - Online Multiplayer Figh...,com.playspare.partyroyaleanimals,Action,NaN,NaN,NaN,NaN,0,False,0.0,...,Playspare,info@playspare.com,NaN,"Mar 30, 2021",Everyone 10+,NaN,True,False,False,2021-06-16 07:21:13

In [95]:
df.drop('Privacy Policy',axis=1,inplace=True)
df.drop('Released',axis=1,inplace=True)

In [96]:
df.isnull().sum()

App Name                0
App Id                  0
Category                0
Rating              22883
Rating Count        22883
Installs              107
Minimum Installs      107
Maximum Installs        0
Free                    0
Price                   0
Currency              135
Size                74973
Minimum Android      6530
Developer Id           33
Developer Email        31
Last Updated            0
Content Rating          0
Ad Supported            0
In App Purchases        0
Editors Choice          0
Scraped Time            0
dtype: int64

In [97]:
df.dropna(subset='Developer Id',inplace=True)

In [98]:
df.dropna(subset='Developer Email',inplace=True)

In [99]:
df.isnull().sum()

App Name                0
App Id                  0
Category                0
Rating              22882
Rating Count        22882
Installs              107
Minimum Installs      107
Maximum Installs        0
Free                    0
Price                   0
Currency              135
Size                74971
Minimum Android      6530
Developer Id            0
Developer Email         0
Last Updated            0
Content Rating          0
Ad Supported            0
In App Purchases        0
Editors Choice          0
Scraped Time            0
dtype: int64

In [100]:
df['Currency'].mode()[0]

'USD'

In [101]:
df['Currency'].fillna(df['Currency'].mode()[0], inplace=True)

C:\Users\butts\AppData\Local\Temp\ipykernel_1500\2664765563.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Currency'].fillna(df['Currency'].mode()[0], inplace=True)

In [102]:
df.isnull().sum()

App Name                0
App Id                  0
Category                0
Rating              22882
Rating Count        22882
Installs              107
Minimum Installs      107
Maximum Installs        0
Free                    0
Price                   0
Currency                0
Size                74971
Minimum Android      6530
Developer Id            0
Developer Email         0
Last Updated            0
Content Rating          0
Ad Supported            0
In App Purchases        0
Editors Choice          0
Scraped Time            0
dtype: int64

In [103]:
df.dropna(subset='Installs',inplace=True)
df.dropna(subset='Minimum Installs',inplace=True)

In [104]:
df['Installs'].unique()

array(['10+', '5,000+', '50+', '100+', '1,000+', '500+', '50,000+',
       '10,000+', '1+', '500,000+', '100,000+', '5+', '10,000,000+',
       '1,000,000+', '5,000,000+', '0+', '100,000,000+', '50,000,000+',
       '1,000,000,000+', '500,000,000+', '5,000,000,000+',
       '10,000,000,000+'], dtype=object)

In [105]:
df['Installs']=df['Installs'].apply(lambda x: x.replace('+','')if'+' in str(x) else x)

In [106]:
df['Installs']=df['Installs'].apply(lambda x: x.replace(',','')if',' in str(x) else x)

In [107]:
df['Installs']= df['Installs'].apply(lambda x: int(x))

In [108]:
df['Installs'].unique()

array([         10,        5000,          50,         100,        1000,
               500,       50000,       10000,           1,      500000,
            100000,           5,    10000000,     1000000,     5000000,
                 0,   100000000,    50000000,  1000000000,   500000000,
        5000000000, 10000000000])

In [109]:
df.describe()

,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Price,Size
count,2.289993e+06,2.289993e+06,2.312768e+06,2.312768e+06,2.312768e+06,2.312768e+06,2.237865e+06
mean,2.203143e+00,2.864919e+03,1.834499e+05,1.834499e+05,3.202210e+05,1.035044e-01,2.716843e+01
std,2.106227e+00,2.121657e+05,1.513166e+07,1.513166e+07,2.355585e+07,2.633226e+00,7.562988e+01
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
25%,0.000000e+00,0.000000e+00,5.000000e+01,5.000000e+01,8.400000e+01,0.000000e+00,5.200000e+00
50%,2.900000e+00,6.000000e+00,5.000000e+02,5.000000e+02,6.950000e+02,0.000000e+00,1.100000e+01
75%,4.300000e+00,4.200000e+01,5.000000e+03,5.000000e+03,7.353000e+03,0.000000e+00,2.600000e+01
max,5.000000e+00,1.385576e+08,1.000000e+10,1.000000e+10,1.205763e+10,4.000000e+02,1.024000e+03

# **Feature Engineering**

In [110]:
bins=[-1,0, 10, 1000, 10000, 100000, 1000000, 10000000, 10000000000]
labels=['no','Very low','low','Moderate','More than Moderate','High','Very High','Top Notch']
df['Installs_Category'] = pd.cut(df['Installs'],bins=bins,labels=labels)

In [111]:
df.head()

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,...,Minimum Android,Developer Id,Developer Email,Last Updated,Content Rating,Ad Supported,In App Purchases,Editors Choice,Scraped Time,Installs_Category
0,Gakondo,com.ishakwe.gakondo,Adventure,0.0,0.0,10,10.0,15,True,0.0,...,7.1 and up,Jean Confident Irénée NIYIZIBYOSE,jean21101999@gmail.com,"Feb 26, 2020",Everyone,False,False,False,2021-06-15 20:19:35,Very low
1,Ampere Battery Info,com.webserveis.batteryinfo,Tools,4.4,64.0,5000,5000.0,7662,True,0.0,...,5.0 and up,Webserveis,webserveis@gmail.com,"May 06, 2021",Everyone,True,False,False,2021-06-15 20:19:35,Moderate
2,Vibook,com.doantiepvien.crm,Productivity,0.0,0.0,50,50.0,58,True,0.0,...,4.0.3 and up,Cabin Crew,vnacrewit@gmail.com,"Aug 19, 2019",Everyone,False,False,False,2021-06-15 20:19:35,low
3,Smart City Trichy Public Service Vehicles 17UC...,cst.stJoseph.ug17ucs548,Communication,5.0,5.0,10,10.0,19,True,0.0,...,4.0.3 and up,Climate Smart Tech2,climatesmarttech2@gmail.com,"Oct 13, 2018",Everyone,True,False,False,2021-06-15 20:19:35,Very low
4,GROW.me,com.horodyski.grower,Tools,0.0,0.0,100,100.0,478,True,0.0,...,4.1 and up,Rafal Milek-Horodyski,rmilekhorodyski@gmail.com,"Nov 12, 2018",Everyone,False,False,False,2021-06-15 20:19:35,low

In [112]:
df.groupby('Installs_Category')['Rating'].describe()

C:\Users\butts\AppData\Local\Temp\ipykernel_1500\3832968905.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Installs_Category')['Rating'].describe()

                        count      mean       std  min  25%  50%  75%  max
Installs_Category
no                    11313.0  0.050438  0.456665  0.0  0.0  0.0  0.0  5.0
Very low             429372.0  0.218208  1.008518  0.0  0.0  0.0  0.0  5.0
low                 1191080.0  2.023189  2.169332  0.0  0.0  0.0  4.4  5.0
Moderate             398576.0  3.815179  0.982820  0.0  3.6  4.1  4.4  5.0
More than Moderate   184885.0  3.885923  0.785328  0.0  3.6  4.1  4.4  5.0
High                  60483.0  4.013457  0.556315  0.0  3.8  4.1  4.4  5.0
Very High             12777.0  4.141723  0.409178  0.0  4.0  4.2  4.4  5.0
Top Notch              1507.0  4.237823  0.341452  1.1  4.1  4.3  4.4  4.9

In [113]:
df['Installs_Category'].loc[df['Rating'].isnull()].value_counts()

Installs_Category
low                   9994
Very low              9898
Moderate              1725
More than Moderate     716
no                     253
High                   178
Very High               10
Top Notch                1
Name: count, dtype: int64

In [114]:
# Step 1: group-wise fill
df['Rating'] = df.groupby('Installs_Category')['Rating'].transform(
    lambda x: x.fillna(x.mean())
)

# Step 2: remaining nulls → overall mean
df['Rating'].fillna(df['Rating'].mean(), inplace=True)

C:\Users\butts\AppData\Local\Temp\ipykernel_1500\2025230419.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df['Rating'] = df.groupby('Installs_Category')['Rating'].transform(
C:\Users\butts\AppData\Local\Temp\ipykernel_1500\2025230419.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Rating'].fillna(df['Rating'].mean(), inplace=True)

In [115]:
df.isnull().sum()

App Name                 0
App Id                   0
Category                 0
Rating                   0
Rating Count         22775
Installs                 0
Minimum Installs         0
Maximum Installs         0
Free                     0
Price                    0
Currency                 0
Size                 74903
Minimum Android       6530
Developer Id             0
Developer Email          0
Last Updated             0
Content Rating           0
Ad Supported             0
In App Purchases         0
Editors Choice           0
Scraped Time             0
Installs_Category        0
dtype: int64

In [116]:
df[df['Rating Count'].duplicated()].head(10)

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,...,Minimum Android,Developer Id,Developer Email,Last Updated,Content Rating,Ad Supported,In App Purchases,Editors Choice,Scraped Time,Installs_Category
2,Vibook,com.doantiepvien.crm,Productivity,0.0,0.0,50,50.0,58,True,0.0,...,4.0.3 and up,Cabin Crew,vnacrewit@gmail.com,"Aug 19, 2019",Everyone,False,False,False,2021-06-15 20:19:35,low
4,GROW.me,com.horodyski.grower,Tools,0.0,0.0,100,100.0,478,True,0.0,...,4.1 and up,Rafal Milek-Horodyski,rmilekhorodyski@gmail.com,"Nov 12, 2018",Everyone,False,False,False,2021-06-15 20:19:35,low
5,IMOCCI,com.imocci,Social,0.0,0.0,50,50.0,89,True,0.0,...,6.0 and up,Imocci GmbH,info@imocci.com,"Dec 20, 2019",Teen,False,True,False,2021-06-15 20:19:35,low
8,WhatsOpen,com.whatsopen.app,Communication,0.0,0.0,10,10.0,18,True,0.0,...,4.4 and up,Yilver Molina Hurtatiz,yilver.mh1996@gmail.com,"Dec 07, 2018",Teen,False,False,False,2021-06-15 20:19:35,Very low
11,Parents,com.eqra.android.BSTS.parent,Maps & Navigation,0.0,0.0,100,100.0,330,True,0.0,...,4.0 and up,Eqra Tech,hhiyassat@eqratech.com,"Jun 27, 2018",Everyone,False,False,False,2021-06-15 20:19:36,low
13,be.MOBILISED,com.hastobe.bemobilised,Maps & Navigation,0.0,0.0,100,100.0,274,True,0.0,...,6.0 and up,has.to.be gmbh,support@has-to-be.com,"May 14, 2021",Everyone,False,False,False,2021-06-15 20:19:36,low
16,OTENTIK Discovery FR,com.camineo.otentikdiscoveryDLFR,Travel & Local,3.4,5.0,500,500.0,949,True,0.0,...,4.4 and up,Hotels Attitude,info@hotels-attitude.com,"Oct 30, 2019",Everyone,False,False,False,2021-06-15 20:19:36,low
19,Contemporary Love Wallpaper HD,com.felingdev.lowalpaper,Books & Reference,0.0,0.0,1,1.0,2,True,0.0,...,4.2 and up,Human Droid Apps,farukabdillah4@gmail.com,"Mar 23, 2021",Mature 17+,True,False,False,2021-06-15 20:19:36,Very low
20,Nepali Congress,np.com.NepaliCongress,Social,0.0,0.0,100,100.0,336,True,0.0,...,5.0 and up,Nitya Shree Developers,info@nepalicongress.org,"May 31, 2021",Everyone,False,False,False,2021-06-15 20:19:36,low
21,Bhavan's BHEL VIM,com.bhavans.vim,Medical,0.0,0.0,10,10.0,31,True,0.0,...,4.0.3 and up,"Bhavans, BHEL, Hyderabad",cheboulu.uma@gmail.com,"Dec 26, 2017",Everyone,False,False,False,2021-06-15 20:19:36,Very low

In [120]:
df['Type'] = df['Free'].map({True: 'Free', False: 'Paid'})
df.head(10)

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,...,Developer Id,Developer Email,Last Updated,Content Rating,Ad Supported,In App Purchases,Editors Choice,Scraped Time,Installs_Category,Type
0,Gakondo,com.ishakwe.gakondo,Adventure,0.0,0.0,10,10.0,15,True,0.0,...,Jean Confident Irénée NIYIZIBYOSE,jean21101999@gmail.com,"Feb 26, 2020",Everyone,False,False,False,2021-06-15 20:19:35,Very low,Free
1,Ampere Battery Info,com.webserveis.batteryinfo,Tools,4.4,64.0,5000,5000.0,7662,True,0.0,...,Webserveis,webserveis@gmail.com,"May 06, 2021",Everyone,True,False,False,2021-06-15 20:19:35,Moderate,Free
2,Vibook,com.doantiepvien.crm,Productivity,0.0,0.0,50,50.0,58,True,0.0,...,Cabin Crew,vnacrewit@gmail.com,"Aug 19, 2019",Everyone,False,False,False,2021-06-15 20:19:35,low,Free
3,Smart City Trichy Public Service Vehicles 17UC...,cst.stJoseph.ug17ucs548,Communication,5.0,5.0,10,10.0,19,True,0.0,...,Climate Smart Tech2,climatesmarttech2@gmail.com,"Oct 13, 2018",Everyone,True,False,False,2021-06-15 20:19:35,Very low,Free
4,GROW.me,com.horodyski.grower,Tools,0.0,0.0,100,100.0,478,True,0.0,...,Rafal Milek-Horodyski,rmilekhorodyski@gmail.com,"Nov 12, 2018",Everyone,False,False,False,2021-06-15 20:19:35,low,Free
5,IMOCCI,com.imocci,Social,0.0,0.0,50,50.0,89,True,0.0,...,Imocci GmbH,info@imocci.com,"Dec 20, 2019",Teen,False,True,False,2021-06-15 20:19:35,low,Free
6,unlimited 4G data prank free app,getfreedata.superfatiza.unlimitedjiodataprank,Libraries & Demo,4.5,12.0,1000,1000.0,2567,True,0.0,...,android developer779,aitomgharfatimezzahra@gmail.com,"Sep 27, 2019",Everyone,True,False,False,2021-06-15 20:19:35,low,Free
7,The Everyday Calendar,com.mozaix.simoneboard,Lifestyle,2.0,39.0,500,500.0,702,True,0.0,...,Mozaix LLC,elementuser03@gmail.com,"Jun 21, 2019",Everyone,False,False,False,2021-06-15 20:19:35,low,Free
8,WhatsOpen,com.whatsopen.app,Communication,0.0,0.0,10,10.0,18,True,0.0,...,Yilver Molina Hurtatiz,yilver.mh1996@gmail.com,"Dec 07, 2018",Teen,False,False,False,2021-06-15 20:19:35,Very low,Free
9,Neon 3d Iron Tech Keyboard Theme,com.ikeyboard.theme.neon_3d.iron.tech,Personalization,4.7,820.0,50000,50000.0,62433,True,0.0,...,Free 2021 Themes for Emoji keyboard,trendyteme.888@gmail.com,"Oct 07, 2020",Everyone,True,False,False,2021-06-15 20:19:35,More than Moderate,Free

In [121]:
df.drop('Free',axis=1,inplace=True)

In [122]:
df.head(10)

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Price,Currency,...,Developer Id,Developer Email,Last Updated,Content Rating,Ad Supported,In App Purchases,Editors Choice,Scraped Time,Installs_Category,Type
0,Gakondo,com.ishakwe.gakondo,Adventure,0.0,0.0,10,10.0,15,0.0,USD,...,Jean Confident Irénée NIYIZIBYOSE,jean21101999@gmail.com,"Feb 26, 2020",Everyone,False,False,False,2021-06-15 20:19:35,Very low,Free
1,Ampere Battery Info,com.webserveis.batteryinfo,Tools,4.4,64.0,5000,5000.0,7662,0.0,USD,...,Webserveis,webserveis@gmail.com,"May 06, 2021",Everyone,True,False,False,2021-06-15 20:19:35,Moderate,Free
2,Vibook,com.doantiepvien.crm,Productivity,0.0,0.0,50,50.0,58,0.0,USD,...,Cabin Crew,vnacrewit@gmail.com,"Aug 19, 2019",Everyone,False,False,False,2021-06-15 20:19:35,low,Free
3,Smart City Trichy Public Service Vehicles 17UC...,cst.stJoseph.ug17ucs548,Communication,5.0,5.0,10,10.0,19,0.0,USD,...,Climate Smart Tech2,climatesmarttech2@gmail.com,"Oct 13, 2018",Everyone,True,False,False,2021-06-15 20:19:35,Very low,Free
4,GROW.me,com.horodyski.grower,Tools,0.0,0.0,100,100.0,478,0.0,USD,...,Rafal Milek-Horodyski,rmilekhorodyski@gmail.com,"Nov 12, 2018",Everyone,False,False,False,2021-06-15 20:19:35,low,Free
5,IMOCCI,com.imocci,Social,0.0,0.0,50,50.0,89,0.0,USD,...,Imocci GmbH,info@imocci.com,"Dec 20, 2019",Teen,False,True,False,2021-06-15 20:19:35,low,Free
6,unlimited 4G data prank free app,getfreedata.superfatiza.unlimitedjiodataprank,Libraries & Demo,4.5,12.0,1000,1000.0,2567,0.0,USD,...,android developer779,aitomgharfatimezzahra@gmail.com,"Sep 27, 2019",Everyone,True,False,False,2021-06-15 20:19:35,low,Free
7,The Everyday Calendar,com.mozaix.simoneboard,Lifestyle,2.0,39.0,500,500.0,702,0.0,USD,...,Mozaix LLC,elementuser03@gmail.com,"Jun 21, 2019",Everyone,False,False,False,2021-06-15 20:19:35,low,Free
8,WhatsOpen,com.whatsopen.app,Communication,0.0,0.0,10,10.0,18,0.0,USD,...,Yilver Molina Hurtatiz,yilver.mh1996@gmail.com,"Dec 07, 2018",Teen,False,False,False,2021-06-15 20:19:35,Very low,Free
9,Neon 3d Iron Tech Keyboard Theme,com.ikeyboard.theme.neon_3d.iron.tech,Personalization,4.7,820.0,50000,50000.0,62433,0.0,USD,...,Free 2021 Themes for Emoji keyboard,trendyteme.888@gmail.com,"Oct 07, 2020",Everyone,True,False,False,2021-06-15 20:19:35,More than Moderate,Free

In [124]:
df['Rating Count'].median()

np.float64(6.0)

In [125]:
df['Rating Count'].fillna(df['Rating Count'].median(), inplace=True)

In [126]:
df.isnull().sum()

App Name                 0
App Id                   0
Category                 0
Rating                   0
Rating Count             0
Installs                 0
Minimum Installs         0
Maximum Installs         0
Price                    0
Currency                 0
Size                 74903
Minimum Android       6530
Developer Id             0
Developer Email          0
Last Updated             0
Content Rating           0
Ad Supported             0
In App Purchases         0
Editors Choice           0
Scraped Time             0
Installs_Category        0
Type                     0
dtype: int64

In [127]:
df['Minimum Android']

0            7.1 and up
1            5.0 and up
2          4.0.3 and up
3          4.0.3 and up
4            4.1 and up
               ...
2312939      4.1 and up
2312940      4.1 and up
2312941      5.0 and up
2312942      5.0 and up
2312943      5.0 and up
Name: Minimum Android, Length: 2312768, dtype: object

In [129]:
df['Minimum Android'] = df['Minimum Android'].str.extract(r'(\d+\.\d+)')
df['Minimum Android'] = df['Minimum Android'].fillna('Unknown')

In [130]:
df.isnull().sum()

App Name                 0
App Id                   0
Category                 0
Rating                   0
Rating Count             0
Installs                 0
Minimum Installs         0
Maximum Installs         0
Price                    0
Currency                 0
Size                 74903
Minimum Android          0
Developer Id             0
Developer Email          0
Last Updated             0
Content Rating           0
Ad Supported             0
In App Purchases         0
Editors Choice           0
Scraped Time             0
Installs_Category        0
Type                     0
dtype: int64

In [133]:
df.dropna(subset='Size',inplace=True)

In [134]:
df.isnull().sum()

App Name             0
App Id               0
Category             0
Rating               0
Rating Count         0
Installs             0
Minimum Installs     0
Maximum Installs     0
Price                0
Currency             0
Size                 0
Minimum Android      0
Developer Id         0
Developer Email      0
Last Updated         0
Content Rating       0
Ad Supported         0
In App Purchases     0
Editors Choice       0
Scraped Time         0
Installs_Category    0
Type                 0
dtype: int64

# *MileStone 1:* **Now our data is cleaned and now we can check duplicates(if any) and can also find insights from the data**

---